"""
What the involution property actually says: a dihedral relation.

In the gauged model every non-root bijection is a perfect matching, so write
A = M_ij, B = M_jl, C = M_li -- three fixed-point-free involutions.  The
triangle condition is that the composite C.B.A is again an involution:

        (C B A)^2 = id   <=>   C B A = A B C .

Multiply on the left by A (an involution) to get

        A (C B) A  =  B C  =  (C B)^{-1} .

So the condition is exactly: **M_ij conjugates M_li . M_jl to its inverse**, i.e.
the group generated by the permutation M_li.M_jl and the involution M_ij is
dihedral, with M_ij acting as a reflection.

That is a much more informative statement than "the composite is a
derangement".  It also shows why no counting obstruction falls out for free:
M_jl and M_li share the index l, so they are edge-disjoint matchings, their
union is a disjoint union of even cycles, and hence the cycles of M_li.M_jl come
in equal-length pairs.  A fixed-point-free involution inverting such a
permutation always exists (pair the equal-length cycles), so the condition is
never vacuously unsatisfiable -- the difficulty is global consistency across
all C(56,3) triples at once, not any single one.

This module verifies the equivalence and the dihedral relation on the Moore
graphs that exist.
"""

from itertools import combinations, permutations

import reduction


def compose(q, p):
    """q . p  (apply p first)."""
    return tuple(q[x] for x in p)


def is_involution(p):
    return all(p[p[x]] == x for x in range(len(p)))


def is_fpf(p):
    return all(p[x] != x for x in range(len(p)))


def inverse(p):
    return reduction.inverse(p)


def gauge(k, sig, m):
    """Relabel each block j by sigma_0j^{-1}, making sigma_0j the identity."""
    out = {}
    idp = tuple(range(m))
    for i in range(k):
        for j in range(k):
            if i == j:
                continue
            a = sig[(0, i)] if i else idp
            b = sig[(0, j)] if j else idp
            binv = inverse(b)
            out[(i, j)] = tuple(binv[sig[(i, j)][a[x]]] for x in range(m))
    return out


def cycle_type(p):
    seen, out = set(), []
    for x in range(len(p)):
        if x in seen:
            continue
        c, y = 0, x
        while y not in seen:
            seen.add(y)
            y = p[y]
            c += 1
        out.append(c)
    return tuple(sorted(out))


def audit(name, g, k):
    m = k - 1
    _, sig = reduction.decompose(g, sorted(g, key=repr)[0])
    G = gauge(k, sig, m)

    matchings = all(is_involution(G[(i, j)]) and is_fpf(G[(i, j)])
                    for i, j in combinations(range(1, k), 2))
    print("  %s" % name)
    print("    gauged M_ij are fixed-point-free involutions : %s" % matchings)

    tot = equiv = dihed = paired = 0
    for i, j, l in permutations(range(1, k), 3):
        A, B, C = G[(i, j)], G[(j, l)], G[(l, i)]
        tot += 1
        lhs = compose(C, compose(B, A))
        rhs = compose(A, compose(B, C))
        # the two formulations must agree
        cond1 = is_involution(lhs)
        cond2 = (lhs == rhs)
        cond3 = compose(A, compose(compose(C, B), A)) == inverse(compose(C, B))
        if cond1 == cond2 == cond3:
            equiv += 1
        if cond3:
            dihed += 1
        # cycles of C.B come in equal-length pairs (B, C disjoint matchings)
        ct = cycle_type(compose(C, B))
        counts = {}
        for c in ct:
            counts[c] = counts.get(c, 0) + 1
        if all(v % 2 == 0 for v in counts.values()):
            paired += 1
    print("    the three formulations agree on                : %d/%d" % (equiv, tot))
    print("    M_ij inverts M_li.M_jl (dihedral)              : %d/%d" % (dihed, tot))
    print("    cycles of M_li.M_jl come in equal-length pairs : %d/%d" % (paired, tot))
    assert equiv == tot
    return dihed == tot


def main():
    print("The involution property as a dihedral relation\n")
    ok3 = audit("Petersen (degree 3)", reduction.petersen(), 3)
    print()
    ok7 = audit("Hoffman-Singleton (degree 7)", reduction.hoffman_singleton(), 7)
    print()
    print("  Both graphs satisfy the dihedral relation on every triple: %s"
          % (ok3 and ok7))
    print()
    print("  Consequence: the condition is never unsatisfiable one triple at a")
    print("  time -- an inverting fixed-point-free involution always exists,")
    print("  because M_jl and M_li share an index, are therefore edge-disjoint,")
    print("  and the product of two disjoint perfect matchings has its cycles")
    print("  in equal-length pairs.  So any obstruction at degree 57 has to be")
    print("  global across all C(56,3) = 27,720 triples, not local.  That is")
    print("  consistent with what the solver shows: four branches are easy,")
    print("  five are already out of reach.")


if __name__ == "__main__":
    main()
